export default {
  // settings images
  mail: require('../assets/img/email.png'),
  storeImg: require('../assets/img/storeImage.png'),
  storeBanner: require('../assets/img/onboard2.png'),
  homeScreenDealImg: require('../assets/img/homeDeal.png'),
  topDealImg: require('../assets/img/topDeal.png'),
  noDealImg: require('../assets/img/noDeal.png'),
  icons: {
    home: require('../assets/icons/home.png'),
    orders: require('../assets/icons/orders.png'),
    profile: require('../assets/icons/profile.png'),
    shop: require('../assets/icons/shop.png'),
    plus: require('../assets/icons/plus.png'),
    eyeOpen: require('../assets/icons/eye-open.png'),
    collection: require('../assets/icons/collection.png'),
    back: require('../assets/icons/back.png'),
    verify: require('../assets/icons/verify.png'),
    location: require('../assets/icons/location.png'),
    starfilled: require('../assets/icons/starfilled.png'),
    stargray: require('../assets/icons/stargray.png'),
    person_round: require('../assets/icons/person-round.png'),
    file: require('../assets/icons/file.png'),
    close: require('../assets/icons/close.png'),
    cart: require('../assets/icons/cart.png'),
    search: require('../assets/icons/search.png'),
    filter: require('../assets/icons/filter.png'),
    clock: require('../assets/icons/clock.png'),
    naira: require('../assets/icons/naira.png'),
    arrowRight: require('../assets/icons/arrow-right.png'),
    arrowDown: require('../assets/icons/arrow-down.png'),
    minus: require('../assets/icons/minus.png'),
    add: require('../assets/icons/add.png'),
    circleCancel: require('../assets/icons/circle-cancel.png'),
    recent: require('../assets/icons/recent.png'),
  },
};
