export default {
  stores: [
    {
      name: 'Juggy Barz',
      verified: true,
      rating: 4.5,
      location: '4, abule oja shina street',
      category: 'Electronic and GAdget',
    },
    {
      name: 'Hamed Sapa store',
      verified: false,
      rating: 4.5,
      location: '4, adesina street olota captain',
      category: 'HouseHold and Offices',
    },
  ],
  homeScreenDeals: [
    {
      dealName: '3kva Elepaq Generator',
      storeName: 'OJB Declutter',
      price: '120,000',
      location: 'Abule oja,Yaba Lagos',
    },
    {
      dealName: '3kva Elepaq Generator',
      storeName: 'OJB Declutter',
      price: '120,000',
      location: 'Abule oja,Yaba Lagos',
    },
  ],
  homeTopDeals: [
    {
      _id: '1',
      storeName: 'OJB Declutter',
      dealDescription: 'Best deals on Household and Electronics ',
      verified: true,
    },
    {
      _id: '2',
      storeName: 'OJB Declutter',
      dealDescription: 'Best deals on Household and Electronics ',
      verified: true,
    },
    {
      _id: '2',
      storeName: 'OJB Declutter',
      dealDescription: 'Best deals on Household and Electronics ',
      verified: true,
    },
    {
      _id: '2',
      storeName: 'OJB Declutter',
      dealDescription: 'Best deals on Household and Electronics ',
      verified: true,
    },
  ],
  AllDealsOfTheDay: [
    {
      dealName: '3kva Elepaq Generator',
      storeName: 'OJB Declutter',
      price: '120,000',
      grade: 'A',
      location: 'Abule oja,Yaba Lagos',
      discountedPrice: '150000',
      canSeeAddress: false,
    },
    {
      dealName: '3kva Elepaq Generator',
      storeName: 'OJB Declutter',
      price: '120,000',
      grade: 'A',
      location: 'Abule oja,Yaba Lagos',
      discountedPrice: '150000',
      canSeeAddress: false,
    },
    {
      dealName: '3kva Elepaq Generator',
      storeName: 'OJB Declutter',
      price: '120,000',
      grade: 'A',
      location: 'Abule oja,Yaba Lagos',
      discountedPrice: '150000',
      canSeeAddress: false,
    },
    {
      dealName: '3kva Elepaq Generator',
      storeName: 'OJB Declutter',
      price: '120,000',
      grade: 'A',
      location: 'Abule oja,Yaba Lagos',
      discountedPrice: '150000',
      canSeeAddress: false,
    },
    {
      dealName: '3kva Elepaq Generator',
      storeName: 'OJB Declutter',
      price: '120,000',
      grade: 'A',
      location: 'Abule oja,Yaba Lagos',
      discountedPrice: '150000',
      canSeeAddress: false,
    },
    {
      dealName: '3kva Elepaq Generator',
      storeName: 'OJB Declutter',
      price: '120,000',
      grade: 'A',
      location: 'Abule oja,Yaba Lagos',
      discountedPrice: '150000',
      canSeeAddress: false,
    },
  ],
  orders: [
    {
      storeName: 'OJB Declutter',
      productName: '3kva Elepaq Gen',
      price: '150000',
    },
  ],
  completedOrders: [
    {
      orderNumber: '32453',
      orderItems: ['1', '2', '3'],
      orderDate: '27th August 2021, 12:00',
      orderStatus: 'completed',
      storeName: 'OJB Declutter',
      cancelled: false,
    },
    {
      orderNumber: '32453',
      orderItems: ['1', '2', '3'],
      orderDate: '27th August 2021, 12:00',
      orderStatus: 'completed',
      storeName: 'OJB Declutter',
      cancelled: true,
    },
  ],
  transactionHistory: [
    {
      date: '27th Feb, 2024. 19:07',
      status: 'cancelled',
      name: 'OJB Declutter',
      order: 'Order 3835565',
    },
    {
      date: '27th Feb, 2024. 19:07',
      status: 'success',
      name: 'OJB Declutter',
      order: 'Order 3835565',
    },
    {
      date: '27th Feb, 2024. 19:07',
      status: 'cancelled',
      name: 'OJB Declutter',
      order: 'Order 3835565',
    },
    {
      date: '27th Feb, 2024. 19:07',
      status: 'cancelled',
      name: 'OJB Declutter',
      order: 'Order 3835565',
    },
    {
      date: '27th Feb, 2024. 19:07',
      status: 'cancelled',
      name: 'OJB Declutter',
      order: 'Order 3835565',
    },
    {
      date: '27th Feb, 2024. 19:07',
      status: 'success',
      name: 'OJB Declutter',
      order: 'Order 3835565',
    },
  ],
};
